# Venture Funding with Deep Learning

You work as a risk management associate at Alphabet Soup, a venture capital firm. Alphabet Soup’s business team receives many funding applications from startups every day. This team has asked you to help them create a model that predicts whether applicants will be successful if funded by Alphabet Soup.

The business team has given you a CSV containing more than 34,000 organizations that have received funding from Alphabet Soup over the years. With your knowledge of machine learning and neural networks, you decide to use the features in the provided dataset to create a binary classifier model that will predict whether an applicant will become a successful business. The CSV file contains a variety of information about these businesses, including whether or not they ultimately became successful.

## Instructions:

The steps for this challenge are broken out into the following sections:

* Prepare the data for use on a neural network model.

* Compile and evaluate a binary classification model using a neural network.

* Optimize the neural network model.

### Prepare the Data for Use on a Neural Network Model 

Using your knowledge of Pandas and scikit-learn’s `StandardScaler()`, preprocess the dataset so that you can use it to compile and evaluate the neural network model later.

Open the starter code file, and complete the following data preparation steps:

1. Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.   

2. Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.
 
3. Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

4. Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course. 

5. Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset. 

6. Split the features and target sets into training and testing datasets.

7. Use scikit-learn's `StandardScaler` to scale the features data.

### Compile and Evaluate a Binary Classification Model Using a Neural Network

Use your knowledge of TensorFlow to design a binary classification deep neural network model. This model should use the dataset’s features to predict whether an Alphabet Soup&ndash;funded startup will be successful based on the features in the dataset. Consider the number of inputs before determining the number of layers that your model will contain or the number of neurons on each layer. Then, compile and fit your model. Finally, evaluate your binary classification model to calculate the model’s loss and accuracy. 
 
To do so, complete the following steps:

1. Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

2. Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

> **Hint** When fitting the model, start with a small number of epochs, such as 20, 50, or 100.

3. Evaluate the model using the test data to determine the model’s loss and accuracy.

4. Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`. 

### Optimize the Neural Network Model

Using your knowledge of TensorFlow and Keras, optimize your model to improve the model's accuracy. Even if you do not successfully achieve a better accuracy, you'll need to demonstrate at least two attempts to optimize the model. You can include these attempts in your existing notebook. Or, you can make copies of the starter notebook in the same folder, rename them, and code each model optimization in a new notebook. 

> **Note** You will not lose points if your model does not achieve a high accuracy, as long as you make at least two attempts to optimize the model.

To do so, complete the following steps:

1. Define at least three new deep neural network models (the original plus 2 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

2. After finishing your models, display the accuracy scores achieved by each model, and compare the results.

3. Save each of your models as an HDF5 file.

In [1]:
# Imports
import pandas as pd
from pathlib import Path
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder

---

## Prepare the data to be used on a neural network model

### Step 1: Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.

In [2]:
from pathlib import Path

# Read the applicants_data.csv file from the Resources folder into a Pandas DataFrame
file_path = Path("Resources/applicants_data.csv")
applicant_data_df = pd.read_csv(file_path)

# Review the DataFrame
applicant_data_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Review the data types associated with the columns
applicant_data_df.dtypes

EIN                        int64
NAME                      object
APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object

### Step 2: Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.

In [4]:
# Drop the 'EIN' and 'NAME' columns from the DataFrame
applicant_data_df = applicant_data_df.drop(['EIN', 'NAME'], axis=1)

# Review the DataFrame
applicant_data_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

### Step 3: Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

In [5]:
# Create a list of categorical variables
categorical_variables = list(applicant_data_df.select_dtypes(include='object').columns)

# Display the categorical variables list
print(categorical_variables)

['APPLICATION_TYPE', 'AFFILIATION', 'CLASSIFICATION', 'USE_CASE', 'ORGANIZATION', 'INCOME_AMT', 'SPECIAL_CONSIDERATIONS']

In [6]:
# Create a OneHotEncoder instance
enc = OneHotEncoder()

In [7]:
# Encode the categorical variables using OneHotEncoder
encoded_data = enc.fit_transform(applicant_data_df[categorical_variables]).toarray()

# Extract the encoded column names
encoded_columns = enc.get_feature_names_out(categorical_variables)

# Create a DataFrame with the encoded variables
encoded_df = pd.DataFrame(encoded_data, columns=encoded_columns)

# Review the DataFrame
encoded_df.head()

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

### Step 4: Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course.

In [8]:
# Add the numerical variables from the original DataFrame to the one-hot encoding DataFrame
encoded_df = pd.concat([encoded_df, applicant_data_df.select_dtypes(include=['int64', 'float64'])], axis=1)

# Review the DataFrame
encoded_df.head()

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y,STATUS,ASK_AMT,IS_SUCCESSFUL
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000,1
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,108590,1
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000,0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,6692,1
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,142590,1

### Step 5: Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset.

In [9]:
# Define the target set y using the IS_SUCCESSFUL column
y = encoded_df['IS_SUCCESSFUL']

# Display a sample of y
print(y.head())

0    1
1    1
2    0
3    1
4    1
Name: IS_SUCCESSFUL, dtype: int64

In [10]:
# Define features set X by selecting all columns but IS_SUCCESSFUL
X = encoded_df.drop('IS_SUCCESSFUL', axis=1)

# Review the features DataFrame
X.head()

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y,STATUS,ASK_AMT
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,108590
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,5000
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,6692
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1,142590

### Step 6: Split the features and target sets into training and testing datasets.

In [11]:
# Split the preprocessed data into a training and testing dataset
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

# Print the shapes of the training and testing datasets
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (25724, 116)
X_test shape: (8575, 116)
y_train shape: (25724,)
y_test shape: (8575,)

### Step 7: Use scikit-learn's `StandardScaler` to scale the features data.

In [12]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the scaler to the features training dataset
X_scaler = scaler.fit(X_train)

# Transform the features training dataset
X_train_scaled = X_scaler.transform(X_train)

# Transform the features testing dataset
X_test_scaled = X_scaler.transform(X_test)

---

## Compile and Evaluate a Binary Classification Model Using a Neural Network

### Step 1: Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

In [13]:
# Define the number of inputs (features) to the model
number_input_features = X_train_scaled.shape[1]

# Review the number of features
print("Number of input features:", number_input_features)

Number of input features: 116

In [14]:
# Define the number of neurons in the output layer
number_output_neurons = 1

In [15]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1 = 4

# Review the number of hidden nodes in the first layer
print("Number of nodes in the first hidden layer:", hidden_nodes_layer1)

Number of nodes in the first hidden layer: 4

In [16]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2 = 5

# Review the number of hidden nodes in the second layer
print("Number of nodes in the second hidden layer:", hidden_nodes_layer2)

Number of nodes in the second hidden layer: 5

In [17]:
# Create the Sequential model instance
nn = Sequential()

In [18]:
# Add the first hidden layer
nn.add(Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

In [19]:
# Add the second hidden layer
nn.add(Dense(units=hidden_nodes_layer2, activation="relu"))

In [20]:
# Add the output layer to the model specifying the number of output neurons and activation function
nn.add(Dense(units=number_output_neurons, activation="sigmoid"))

In [21]:
# Display the Sequential model summary
print(nn.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 4)                 468

 dense_1 (Dense)             (None, 5)                 25

 dense_2 (Dense)             (None, 1)                 6

=================================================================
Total params: 499 (1.95 KB)
Trainable params: 499 (1.95 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None

### Step 2: Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

In [22]:
# Compile the Sequential model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [23]:
# Fit the model using 50 epochs and the training data
nn.fit(X_train_scaled, y_train, epochs=50, verbose=2)

Epoch 1/50
804/804 - 0s - loss: 0.6413 - accuracy: 0.6637 - 402ms/epoch - 500us/step
Epoch 2/50
804/804 - 0s - loss: 0.5831 - accuracy: 0.7170 - 256ms/epoch - 318us/step
Epoch 3/50
804/804 - 0s - loss: 0.5674 - accuracy: 0.7263 - 241ms/epoch - 300us/step
Epoch 4/50
804/804 - 0s - loss: 0.5607 - accuracy: 0.7273 - 242ms/epoch - 301us/step
Epoch 5/50
804/804 - 0s - loss: 0.5568 - accuracy: 0.7284 - 241ms/epoch - 299us/step
Epoch 6/50
804/804 - 0s - loss: 0.5540 - accuracy: 0.7290 - 242ms/epoch - 301us/step
Epoch 7/50
804/804 - 0s - loss: 0.5524 - accuracy: 0.7307 - 241ms/epoch - 300us/step
Epoch 8/50
804/804 - 0s - loss: 0.5518 - accuracy: 0.7301 - 242ms/epoch - 301us/step
Epoch 9/50
804/804 - 0s - loss: 0.5512 - accuracy: 0.7296 - 240ms/epoch - 298us/step
Epoch 10/50
804/804 - 0s - loss: 0.5505 - accuracy: 0.7313 - 243ms/epoch - 302us/step
Epoch 11/50
804/804 - 0s - loss: 0.5500 - accuracy: 0.7322 - 241ms/epoch - 300us/step
Epoch 12/50
804/804 - 0s - loss: 0.5499 - accuracy: 0.7315 - 241ms/epoch - 300us/step
Epoch 13/50
804/804 - 0s - loss: 0.5493 - accuracy: 0.7317 - 241ms/epoch - 300us/step
Epoch 14/50
804/804 - 0s - loss: 0.5497 - accuracy: 0.7317 - 241ms/epoch - 299us/step
Epoch 15/50
804/804 - 0s - loss: 0.5489 - accuracy: 0.7318 - 239ms/epoch - 298us/step
Epoch 16/50
804/804 - 0s - loss: 0.5489 - accuracy: 0.7322 - 242ms/epoch - 301us/step
Epoch 17/50
804/804 - 0s - loss: 0.5485 - accuracy: 0.7320 - 243ms/epoch - 302us/step
Epoch 18/50
804/804 - 0s - loss: 0.5487 - accuracy: 0.7325 - 240ms/epoch - 299us/step
Epoch 19/50
804/804 - 0s - loss: 0.5485 - accuracy: 0.7321 - 240ms/epoch - 299us/step
Epoch 20/50
804/804 - 0s - loss: 0.5483 - accuracy: 0.7328 - 254ms/epoch - 316us/step
Epoch 21/50
804/804 - 0s - loss: 0.5483 - accuracy: 0.7322 - 242ms/epoch - 302us/step
Epoch 22/50
804/804 - 0s - loss: 0.5481 - accuracy: 0.7323 - 241ms/epoch - 300us/step
Epoch 23/50
804/804 - 0s - loss: 0.5482 - accuracy: 0.7323 - 241ms/epoch - 299us/step
Epoch 24/50
804/804 - 0s - loss: 0.5479 - accuracy: 0.7317 - 241ms/epoch - 300us/step
Epoch 25/50
804/804 - 0s - loss: 0.5478 - accuracy: 0.7334 - 240ms/epoch - 299us/step
Epoch 26/50
804/804 - 0s - loss: 0.5479 - accuracy: 0.7331 - 244ms/epoch - 303us/step
Epoch 27/50
804/804 - 0s - loss: 0.5478 - accuracy: 0.7325 - 241ms/epoch - 300us/step
Epoch 28/50
804/804 - 0s - loss: 0.5476 - accuracy: 0.7317 - 242ms/epoch - 301us/step
Epoch 29/50
804/804 - 0s - loss: 0.5479 - accuracy: 0.7326 - 247ms/epoch - 307us/step
Epoch 30/50
804/804 - 0s - loss: 0.5474 - accuracy: 0.7318 - 242ms/epoch - 301us/step
Epoch 31/50
804/804 - 0s - loss: 0.5473 - accuracy: 0.7322 - 240ms/epoch - 299us/step
Epoch 32/50
804/804 - 0s - loss: 0.5472 - accuracy: 0.7333 - 241ms/epoch - 299us/step
Epoch 33/50
804/804 - 0s - loss: 0.5472 - accuracy: 0.7324 - 242ms/epoch - 301us/step
Epoch 34/50
804/804 - 0s - loss: 0.5471 - accuracy: 0.7315 - 241ms/epoch - 300us/step
Epoch 35/50
804/804 - 0s - loss: 0.5472 - accuracy: 0.7327 - 240ms/epoch - 299us/step
Epoch 36/50
804/804 - 0s - loss: 0.5470 - accuracy: 0.7334 - 241ms/epoch - 299us/step
Epoch 37/50
804/804 - 0s - loss: 0.5471 - accuracy: 0.7332 - 255ms/epoch - 317us/step
Epoch 38/50
804/804 - 0s - loss: 0.5471 - accuracy: 0.7324 - 240ms/epoch - 298us/step
Epoch 39/50
804/804 - 0s - loss: 0.5470 - accuracy: 0.7322 - 242ms/epoch - 301us/step
Epoch 40/50
804/804 - 0s - loss: 0.5467 - accuracy: 0.7332 - 241ms/epoch - 300us/step
Epoch 41/50
804/804 - 0s - loss: 0.5469 - accuracy: 0.7331 - 242ms/epoch - 301us/step
Epoch 42/50
804/804 - 0s - loss: 0.5465 - accuracy: 0.7330 - 241ms/epoch - 300us/step
Epoch 43/50
804/804 - 0s - loss: 0.5470 - accuracy: 0.7331 - 242ms/epoch - 301us/step
Epoch 44/50
804/804 - 0s - loss: 0.5463 - accuracy: 0.7338 - 241ms/epoch - 300us/step
Epoch 45/50
804/804 - 0s - loss: 0.5468 - accuracy: 0.7333 - 244ms/epoch - 304us/step
Epoch 46/50
804/804 - 0s - loss: 0.5465 - accuracy: 0.7331 - 245ms/epoch - 305us/step
Epoch 47/50
804/804 - 0s - loss: 0.5466 - accuracy: 0.7339 - 242ms/epoch - 301us/step
Epoch 48/50
804/804 - 0s - loss: 0.5464 - accuracy: 0.7328 - 240ms/epoch - 298us/step
Epoch 49/50
804/804 - 0s - loss: 0.5463 - accuracy: 0.7327 - 241ms/epoch - 300us/step
Epoch 50/50
804/804 - 0s - loss: 0.5463 - accuracy: 0.7331 - 241ms/epoch - 300us/step

### Step 3: Evaluate the model using the test data to determine the model’s loss and accuracy.

In [24]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5550 - accuracy: 0.7276 - 116ms/epoch - 432us/step
Loss: 0.554974377155304, Accuracy: 0.727580189704895

### Step 4: Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`.

In [25]:
# Set the model's file path
file_path = "AlphabetSoup.h5"

# Export your model to a HDF5 file
nn.save(file_path)

/Users/isabel/miniforge3/lib/python3.10/site-packages/keras/src/engine/training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

---

## Optimize the neural network model

### Step 1: Define at least three new deep neural network models (resulting in the original plus 3 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

### Alternative Model 1

In [26]:
# Define the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
print("Number of input features:", number_input_features)

Number of input features: 116

In [27]:
# Define the number of neurons in the output layer
number_output_neurons_A1 = 1

In [28]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A1 = 8

# Review the number of hidden nodes in the first layer
print("Number of nodes in the first hidden layer:", hidden_nodes_layer1_A1)

Number of nodes in the first hidden layer: 8

In [29]:
# Create the Sequential model instance
nn_A1 = Sequential()

In [30]:
# First hidden layer
nn_A1.add(Dense(units=hidden_nodes_layer1_A1, input_dim=number_input_features, activation="relu"))

# Output layer
nn_A1.add(Dense(units=number_output_neurons_A1, activation="sigmoid"))

# Check the structure of the model
print(nn_A1.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 8)                 936

 dense_4 (Dense)             (None, 1)                 9

=================================================================
Total params: 945 (3.69 KB)
Trainable params: 945 (3.69 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None

In [31]:
# Compile the Sequential model
nn_A1.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [32]:
# Fit the model using 50 epochs and the training data
fit_model_A1 = nn_A1.fit(X_train_scaled, y_train, epochs=100, verbose=2)

Epoch 1/100
804/804 - 0s - loss: 0.6352 - accuracy: 0.7000 - 352ms/epoch - 437us/step
Epoch 2/100
804/804 - 0s - loss: 0.5783 - accuracy: 0.7259 - 236ms/epoch - 293us/step
Epoch 3/100
804/804 - 0s - loss: 0.5658 - accuracy: 0.7272 - 247ms/epoch - 307us/step
Epoch 4/100
804/804 - 0s - loss: 0.5594 - accuracy: 0.7282 - 254ms/epoch - 316us/step
Epoch 5/100
804/804 - 0s - loss: 0.5565 - accuracy: 0.7288 - 251ms/epoch - 312us/step
Epoch 6/100
804/804 - 0s - loss: 0.5543 - accuracy: 0.7286 - 255ms/epoch - 317us/step
Epoch 7/100
804/804 - 0s - loss: 0.5526 - accuracy: 0.7297 - 256ms/epoch - 318us/step
Epoch 8/100
804/804 - 0s - loss: 0.5515 - accuracy: 0.7296 - 255ms/epoch - 317us/step
Epoch 9/100
804/804 - 0s - loss: 0.5501 - accuracy: 0.7301 - 256ms/epoch - 318us/step
Epoch 10/100
804/804 - 0s - loss: 0.5495 - accuracy: 0.7305 - 253ms/epoch - 315us/step
Epoch 11/100
804/804 - 0s - loss: 0.5487 - accuracy: 0.7301 - 255ms/epoch - 317us/step
Epoch 12/100
804/804 - 0s - loss: 0.5481 - accuracy: 0.7298 - 272ms/epoch - 338us/step
Epoch 13/100
804/804 - 0s - loss: 0.5476 - accuracy: 0.7304 - 255ms/epoch - 317us/step
Epoch 14/100
804/804 - 0s - loss: 0.5472 - accuracy: 0.7321 - 254ms/epoch - 316us/step
Epoch 15/100
804/804 - 0s - loss: 0.5470 - accuracy: 0.7308 - 254ms/epoch - 316us/step
Epoch 16/100
804/804 - 0s - loss: 0.5470 - accuracy: 0.7315 - 253ms/epoch - 314us/step
Epoch 17/100
804/804 - 0s - loss: 0.5468 - accuracy: 0.7313 - 253ms/epoch - 315us/step
Epoch 18/100
804/804 - 0s - loss: 0.5463 - accuracy: 0.7322 - 253ms/epoch - 314us/step
Epoch 19/100
804/804 - 0s - loss: 0.5456 - accuracy: 0.7322 - 250ms/epoch - 311us/step
Epoch 20/100
804/804 - 0s - loss: 0.5459 - accuracy: 0.7324 - 256ms/epoch - 319us/step
Epoch 21/100
804/804 - 0s - loss: 0.5454 - accuracy: 0.7317 - 254ms/epoch - 316us/step
Epoch 22/100
804/804 - 0s - loss: 0.5450 - accuracy: 0.7322 - 249ms/epoch - 310us/step
Epoch 23/100
804/804 - 0s - loss: 0.5453 - accuracy: 0.7324 - 256ms/epoch - 318us/step
Epoch 24/100
804/804 - 0s - loss: 0.5454 - accuracy: 0.7311 - 253ms/epoch - 315us/step
Epoch 25/100
804/804 - 0s - loss: 0.5450 - accuracy: 0.7316 - 253ms/epoch - 314us/step
Epoch 26/100
804/804 - 0s - loss: 0.5451 - accuracy: 0.7318 - 253ms/epoch - 314us/step
Epoch 27/100
804/804 - 0s - loss: 0.5450 - accuracy: 0.7317 - 253ms/epoch - 315us/step
Epoch 28/100
804/804 - 0s - loss: 0.5447 - accuracy: 0.7325 - 252ms/epoch - 313us/step
Epoch 29/100
804/804 - 0s - loss: 0.5446 - accuracy: 0.7326 - 253ms/epoch - 314us/step
Epoch 30/100
804/804 - 0s - loss: 0.5446 - accuracy: 0.7310 - 271ms/epoch - 336us/step
Epoch 31/100
804/804 - 0s - loss: 0.5445 - accuracy: 0.7311 - 254ms/epoch - 316us/step
Epoch 32/100
804/804 - 0s - loss: 0.5443 - accuracy: 0.7318 - 254ms/epoch - 316us/step
Epoch 33/100
804/804 - 0s - loss: 0.5444 - accuracy: 0.7318 - 250ms/epoch - 312us/step
Epoch 34/100
804/804 - 0s - loss: 0.5443 - accuracy: 0.7322 - 254ms/epoch - 316us/step
Epoch 35/100
804/804 - 0s - loss: 0.5436 - accuracy: 0.7324 - 254ms/epoch - 316us/step
Epoch 36/100
804/804 - 0s - loss: 0.5441 - accuracy: 0.7324 - 253ms/epoch - 314us/step
Epoch 37/100
804/804 - 0s - loss: 0.5438 - accuracy: 0.7329 - 256ms/epoch - 319us/step
Epoch 38/100
804/804 - 0s - loss: 0.5437 - accuracy: 0.7329 - 259ms/epoch - 322us/step
Epoch 39/100
804/804 - 0s - loss: 0.5438 - accuracy: 0.7329 - 250ms/epoch - 311us/step
Epoch 40/100
804/804 - 0s - loss: 0.5435 - accuracy: 0.7329 - 253ms/epoch - 314us/step
Epoch 41/100
804/804 - 0s - loss: 0.5440 - accuracy: 0.7326 - 250ms/epoch - 311us/step
Epoch 42/100
804/804 - 0s - loss: 0.5437 - accuracy: 0.7327 - 254ms/epoch - 316us/step
Epoch 43/100
804/804 - 0s - loss: 0.5437 - accuracy: 0.7327 - 257ms/epoch - 320us/step
Epoch 44/100
804/804 - 0s - loss: 0.5433 - accuracy: 0.7328 - 254ms/epoch - 316us/step
Epoch 45/100
804/804 - 0s - loss: 0.5433 - accuracy: 0.7323 - 256ms/epoch - 319us/step
Epoch 46/100
804/804 - 0s - loss: 0.5433 - accuracy: 0.7338 - 255ms/epoch - 317us/step
Epoch 47/100
804/804 - 0s - loss: 0.5430 - accuracy: 0.7335 - 264ms/epoch - 329us/step
Epoch 48/100
804/804 - 0s - loss: 0.5431 - accuracy: 0.7324 - 233ms/epoch - 289us/step
Epoch 49/100
804/804 - 0s - loss: 0.5427 - accuracy: 0.7327 - 239ms/epoch - 297us/step
Epoch 50/100
804/804 - 0s - loss: 0.5430 - accuracy: 0.7323 - 232ms/epoch - 289us/step
Epoch 51/100
804/804 - 0s - loss: 0.5422 - accuracy: 0.7334 - 231ms/epoch - 287us/step
Epoch 52/100
804/804 - 0s - loss: 0.5427 - accuracy: 0.7316 - 231ms/epoch - 287us/step
Epoch 53/100
804/804 - 0s - loss: 0.5426 - accuracy: 0.7331 - 232ms/epoch - 288us/step
Epoch 54/100
804/804 - 0s - loss: 0.5423 - accuracy: 0.7326 - 232ms/epoch - 288us/step
Epoch 55/100
804/804 - 0s - loss: 0.5423 - accuracy: 0.7327 - 233ms/epoch - 290us/step
Epoch 56/100
804/804 - 0s - loss: 0.5425 - accuracy: 0.7332 - 233ms/epoch - 289us/step
Epoch 57/100
804/804 - 0s - loss: 0.5423 - accuracy: 0.7322 - 232ms/epoch - 289us/step
Epoch 58/100
804/804 - 0s - loss: 0.5421 - accuracy: 0.7329 - 232ms/epoch - 288us/step
Epoch 59/100
804/804 - 0s - loss: 0.5423 - accuracy: 0.7329 - 232ms/epoch - 288us/step
Epoch 60/100
804/804 - 0s - loss: 0.5422 - accuracy: 0.7335 - 232ms/epoch - 289us/step
Epoch 61/100
804/804 - 0s - loss: 0.5420 - accuracy: 0.7322 - 231ms/epoch - 288us/step
Epoch 62/100
804/804 - 0s - loss: 0.5421 - accuracy: 0.7338 - 232ms/epoch - 289us/step
Epoch 63/100
804/804 - 0s - loss: 0.5423 - accuracy: 0.7326 - 245ms/epoch - 305us/step
Epoch 64/100
804/804 - 0s - loss: 0.5418 - accuracy: 0.7336 - 230ms/epoch - 286us/step
Epoch 65/100
804/804 - 0s - loss: 0.5420 - accuracy: 0.7333 - 231ms/epoch - 288us/step
Epoch 66/100
804/804 - 0s - loss: 0.5420 - accuracy: 0.7345 - 230ms/epoch - 286us/step
Epoch 67/100
804/804 - 0s - loss: 0.5418 - accuracy: 0.7332 - 231ms/epoch - 288us/step
Epoch 68/100
804/804 - 0s - loss: 0.5421 - accuracy: 0.7331 - 232ms/epoch - 289us/step
Epoch 69/100
804/804 - 0s - loss: 0.5419 - accuracy: 0.7339 - 231ms/epoch - 287us/step
Epoch 70/100
804/804 - 0s - loss: 0.5419 - accuracy: 0.7338 - 232ms/epoch - 288us/step
Epoch 71/100
804/804 - 0s - loss: 0.5418 - accuracy: 0.7334 - 233ms/epoch - 290us/step
Epoch 72/100
804/804 - 0s - loss: 0.5419 - accuracy: 0.7338 - 232ms/epoch - 289us/step
Epoch 73/100
804/804 - 0s - loss: 0.5417 - accuracy: 0.7335 - 232ms/epoch - 288us/step
Epoch 74/100
804/804 - 0s - loss: 0.5418 - accuracy: 0.7333 - 232ms/epoch - 288us/step
Epoch 75/100
804/804 - 0s - loss: 0.5419 - accuracy: 0.7341 - 232ms/epoch - 289us/step
Epoch 76/100
804/804 - 0s - loss: 0.5415 - accuracy: 0.7342 - 242ms/epoch - 301us/step
Epoch 77/100
804/804 - 0s - loss: 0.5416 - accuracy: 0.7334 - 252ms/epoch - 313us/step
Epoch 78/100
804/804 - 0s - loss: 0.5416 - accuracy: 0.7341 - 245ms/epoch - 305us/step
Epoch 79/100
804/804 - 0s - loss: 0.5416 - accuracy: 0.7340 - 232ms/epoch - 288us/step
Epoch 80/100
804/804 - 0s - loss: 0.5415 - accuracy: 0.7335 - 231ms/epoch - 288us/step
Epoch 81/100
804/804 - 0s - loss: 0.5414 - accuracy: 0.7336 - 233ms/epoch - 290us/step
Epoch 82/100
804/804 - 0s - loss: 0.5416 - accuracy: 0.7339 - 232ms/epoch - 288us/step
Epoch 83/100
804/804 - 0s - loss: 0.5414 - accuracy: 0.7342 - 232ms/epoch - 289us/step
Epoch 84/100
804/804 - 0s - loss: 0.5414 - accuracy: 0.7337 - 234ms/epoch - 291us/step
Epoch 85/100
804/804 - 0s - loss: 0.5414 - accuracy: 0.7341 - 234ms/epoch - 291us/step
Epoch 86/100
804/804 - 0s - loss: 0.5414 - accuracy: 0.7339 - 232ms/epoch - 288us/step
Epoch 87/100
804/804 - 0s - loss: 0.5414 - accuracy: 0.7337 - 231ms/epoch - 287us/step
Epoch 88/100
804/804 - 0s - loss: 0.5412 - accuracy: 0.7338 - 232ms/epoch - 289us/step
Epoch 89/100
804/804 - 0s - loss: 0.5416 - accuracy: 0.7337 - 231ms/epoch - 288us/step
Epoch 90/100
804/804 - 0s - loss: 0.5413 - accuracy: 0.7342 - 233ms/epoch - 290us/step
Epoch 91/100
804/804 - 0s - loss: 0.5412 - accuracy: 0.7345 - 234ms/epoch - 291us/step
Epoch 92/100
804/804 - 0s - loss: 0.5411 - accuracy: 0.7340 - 246ms/epoch - 306us/step
Epoch 93/100
804/804 - 0s - loss: 0.5412 - accuracy: 0.7339 - 231ms/epoch - 288us/step
Epoch 94/100
804/804 - 0s - loss: 0.5413 - accuracy: 0.7327 - 231ms/epoch - 288us/step
Epoch 95/100
804/804 - 0s - loss: 0.5412 - accuracy: 0.7333 - 232ms/epoch - 289us/step
Epoch 96/100
804/804 - 0s - loss: 0.5410 - accuracy: 0.7344 - 231ms/epoch - 287us/step
Epoch 97/100
804/804 - 0s - loss: 0.5410 - accuracy: 0.7337 - 232ms/epoch - 288us/step
Epoch 98/100
804/804 - 0s - loss: 0.5412 - accuracy: 0.7337 - 232ms/epoch - 288us/step
Epoch 99/100
804/804 - 0s - loss: 0.5411 - accuracy: 0.7343 - 231ms/epoch - 288us/step
Epoch 100/100
804/804 - 0s - loss: 0.5410 - accuracy: 0.7344 - 233ms/epoch - 290us/step

#### Alternative Model 2

In [88]:
from tensorflow.keras.layers import Dense, Dropout

In [89]:
# Define the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
print("Number of input features:", number_input_features)

Number of input features: 116

In [90]:
# Define the number of neurons in the output layer
number_output_neurons_A2 = 1

In [91]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A2 = 8

# Define the dropout rate
dropout_rate = 0.3

# Review the number of hidden nodes in the first layer
print("Number of nodes in the first hidden layer:", hidden_nodes_layer1_A2)

Number of nodes in the first hidden layer: 8

In [92]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2_A2 = 6

# Review the number of hidden nodes in the first layer
print("Number of nodes in the first hidden layer:", hidden_nodes_layer2_A2)

Number of nodes in the first hidden layer: 6

In [93]:
# Create the Sequential model instance
nn_A2 = Sequential()

In [94]:
# First hidden layer
nn_A2.add(Dense(units=hidden_nodes_layer1_A2, input_dim=number_input_features, activation="relu"))

# Add a dropout layer
nn_A2.add(Dropout(dropout_rate))

# Second hidden layer
nn_A2.add(Dense(units=hidden_nodes_layer1_A2, activation="relu"))

# Add another dropout layer
nn_A2.add(Dropout(dropout_rate))

# Output layer
nn_A2.add(Dense(units=number_output_neurons_A2, activation="sigmoid"))

# Check the structure of the model
print(nn_A2.summary())

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_17 (Dense)            (None, 8)                 936

 dropout_8 (Dropout)         (None, 8)                 0

 dense_18 (Dense)            (None, 8)                 72

 dropout_9 (Dropout)         (None, 8)                 0

 dense_19 (Dense)            (None, 1)                 9

=================================================================
Total params: 1017 (3.97 KB)
Trainable params: 1017 (3.97 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None

In [95]:
# Compile the model
nn_A2.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [96]:
# Fit the model
fit_model_A2 = nn_A2.fit(X_train_scaled, y_train, epochs=100, verbose=2)

Epoch 1/100
804/804 - 0s - loss: 0.6681 - accuracy: 0.6394 - 415ms/epoch - 517us/step
Epoch 2/100
804/804 - 0s - loss: 0.6209 - accuracy: 0.6847 - 261ms/epoch - 325us/step
Epoch 3/100
804/804 - 0s - loss: 0.6060 - accuracy: 0.6996 - 261ms/epoch - 324us/step
Epoch 4/100
804/804 - 0s - loss: 0.5950 - accuracy: 0.7102 - 258ms/epoch - 321us/step
Epoch 5/100
804/804 - 0s - loss: 0.5913 - accuracy: 0.7103 - 258ms/epoch - 320us/step
Epoch 6/100
804/804 - 0s - loss: 0.5889 - accuracy: 0.7144 - 260ms/epoch - 323us/step
Epoch 7/100
804/804 - 0s - loss: 0.5849 - accuracy: 0.7149 - 258ms/epoch - 321us/step
Epoch 8/100
804/804 - 0s - loss: 0.5807 - accuracy: 0.7182 - 258ms/epoch - 321us/step
Epoch 9/100
804/804 - 0s - loss: 0.5807 - accuracy: 0.7178 - 257ms/epoch - 320us/step
Epoch 10/100
804/804 - 0s - loss: 0.5764 - accuracy: 0.7189 - 261ms/epoch - 325us/step
Epoch 11/100
804/804 - 0s - loss: 0.5731 - accuracy: 0.7210 - 258ms/epoch - 321us/step
Epoch 12/100
804/804 - 0s - loss: 0.5766 - accuracy: 0.7205 - 257ms/epoch - 319us/step
Epoch 13/100
804/804 - 0s - loss: 0.5752 - accuracy: 0.7214 - 257ms/epoch - 320us/step
Epoch 14/100
804/804 - 0s - loss: 0.5740 - accuracy: 0.7206 - 261ms/epoch - 324us/step
Epoch 15/100
804/804 - 0s - loss: 0.5734 - accuracy: 0.7217 - 258ms/epoch - 321us/step
Epoch 16/100
804/804 - 0s - loss: 0.5761 - accuracy: 0.7219 - 257ms/epoch - 320us/step
Epoch 17/100
804/804 - 0s - loss: 0.5730 - accuracy: 0.7219 - 256ms/epoch - 319us/step
Epoch 18/100
804/804 - 0s - loss: 0.5759 - accuracy: 0.7201 - 259ms/epoch - 322us/step
Epoch 19/100
804/804 - 0s - loss: 0.5728 - accuracy: 0.7209 - 259ms/epoch - 322us/step
Epoch 20/100
804/804 - 0s - loss: 0.5750 - accuracy: 0.7204 - 258ms/epoch - 320us/step
Epoch 21/100
804/804 - 0s - loss: 0.5729 - accuracy: 0.7235 - 257ms/epoch - 320us/step
Epoch 22/100
804/804 - 0s - loss: 0.5728 - accuracy: 0.7190 - 259ms/epoch - 322us/step
Epoch 23/100
804/804 - 0s - loss: 0.5735 - accuracy: 0.7196 - 257ms/epoch - 320us/step
Epoch 24/100
804/804 - 0s - loss: 0.5718 - accuracy: 0.7224 - 272ms/epoch - 338us/step
Epoch 25/100
804/804 - 0s - loss: 0.5730 - accuracy: 0.7219 - 257ms/epoch - 320us/step
Epoch 26/100
804/804 - 0s - loss: 0.5726 - accuracy: 0.7200 - 257ms/epoch - 320us/step
Epoch 27/100
804/804 - 0s - loss: 0.5724 - accuracy: 0.7216 - 257ms/epoch - 320us/step
Epoch 28/100
804/804 - 0s - loss: 0.5724 - accuracy: 0.7219 - 256ms/epoch - 319us/step
Epoch 29/100
804/804 - 0s - loss: 0.5729 - accuracy: 0.7210 - 256ms/epoch - 318us/step
Epoch 30/100
804/804 - 0s - loss: 0.5716 - accuracy: 0.7221 - 259ms/epoch - 322us/step
Epoch 31/100
804/804 - 0s - loss: 0.5735 - accuracy: 0.7222 - 258ms/epoch - 321us/step
Epoch 32/100
804/804 - 0s - loss: 0.5693 - accuracy: 0.7243 - 259ms/epoch - 322us/step
Epoch 33/100
804/804 - 0s - loss: 0.5724 - accuracy: 0.7212 - 258ms/epoch - 321us/step
Epoch 34/100
804/804 - 0s - loss: 0.5719 - accuracy: 0.7206 - 258ms/epoch - 320us/step
Epoch 35/100
804/804 - 0s - loss: 0.5756 - accuracy: 0.7196 - 256ms/epoch - 319us/step
Epoch 36/100
804/804 - 0s - loss: 0.5709 - accuracy: 0.7224 - 258ms/epoch - 321us/step
Epoch 37/100
804/804 - 0s - loss: 0.5727 - accuracy: 0.7208 - 258ms/epoch - 322us/step
Epoch 38/100
804/804 - 0s - loss: 0.5735 - accuracy: 0.7210 - 260ms/epoch - 323us/step
Epoch 39/100
804/804 - 0s - loss: 0.5712 - accuracy: 0.7211 - 257ms/epoch - 320us/step
Epoch 40/100
804/804 - 0s - loss: 0.5724 - accuracy: 0.7219 - 259ms/epoch - 322us/step
Epoch 41/100
804/804 - 0s - loss: 0.5718 - accuracy: 0.7215 - 256ms/epoch - 319us/step
Epoch 42/100
804/804 - 0s - loss: 0.5711 - accuracy: 0.7224 - 272ms/epoch - 338us/step
Epoch 43/100
804/804 - 0s - loss: 0.5697 - accuracy: 0.7238 - 259ms/epoch - 322us/step
Epoch 44/100
804/804 - 0s - loss: 0.5723 - accuracy: 0.7227 - 257ms/epoch - 320us/step
Epoch 45/100
804/804 - 0s - loss: 0.5712 - accuracy: 0.7254 - 257ms/epoch - 320us/step
Epoch 46/100
804/804 - 0s - loss: 0.5708 - accuracy: 0.7190 - 257ms/epoch - 320us/step
Epoch 47/100
804/804 - 0s - loss: 0.5737 - accuracy: 0.7224 - 260ms/epoch - 323us/step
Epoch 48/100
804/804 - 0s - loss: 0.5726 - accuracy: 0.7208 - 258ms/epoch - 321us/step
Epoch 49/100
804/804 - 0s - loss: 0.5702 - accuracy: 0.7202 - 258ms/epoch - 320us/step
Epoch 50/100
804/804 - 0s - loss: 0.5697 - accuracy: 0.7230 - 258ms/epoch - 321us/step
Epoch 51/100
804/804 - 0s - loss: 0.5721 - accuracy: 0.7218 - 258ms/epoch - 321us/step
Epoch 52/100
804/804 - 0s - loss: 0.5720 - accuracy: 0.7230 - 256ms/epoch - 319us/step
Epoch 53/100
804/804 - 0s - loss: 0.5694 - accuracy: 0.7211 - 256ms/epoch - 319us/step
Epoch 54/100
804/804 - 0s - loss: 0.5722 - accuracy: 0.7189 - 259ms/epoch - 322us/step
Epoch 55/100
804/804 - 0s - loss: 0.5724 - accuracy: 0.7232 - 258ms/epoch - 321us/step
Epoch 56/100
804/804 - 0s - loss: 0.5701 - accuracy: 0.7224 - 257ms/epoch - 320us/step
Epoch 57/100
804/804 - 0s - loss: 0.5696 - accuracy: 0.7229 - 256ms/epoch - 319us/step
Epoch 58/100
804/804 - 0s - loss: 0.5724 - accuracy: 0.7201 - 257ms/epoch - 320us/step
Epoch 59/100
804/804 - 0s - loss: 0.5696 - accuracy: 0.7219 - 259ms/epoch - 322us/step
Epoch 60/100
804/804 - 0s - loss: 0.5687 - accuracy: 0.7229 - 270ms/epoch - 336us/step
Epoch 61/100
804/804 - 0s - loss: 0.5695 - accuracy: 0.7231 - 257ms/epoch - 319us/step
Epoch 62/100
804/804 - 0s - loss: 0.5736 - accuracy: 0.7215 - 255ms/epoch - 318us/step
Epoch 63/100
804/804 - 0s - loss: 0.5699 - accuracy: 0.7234 - 259ms/epoch - 322us/step
Epoch 64/100
804/804 - 0s - loss: 0.5711 - accuracy: 0.7216 - 257ms/epoch - 319us/step
Epoch 65/100
804/804 - 0s - loss: 0.5717 - accuracy: 0.7228 - 257ms/epoch - 320us/step
Epoch 66/100
804/804 - 0s - loss: 0.5717 - accuracy: 0.7226 - 258ms/epoch - 321us/step
Epoch 67/100
804/804 - 0s - loss: 0.5714 - accuracy: 0.7222 - 261ms/epoch - 325us/step
Epoch 68/100
804/804 - 0s - loss: 0.5678 - accuracy: 0.7248 - 258ms/epoch - 321us/step
Epoch 69/100
804/804 - 0s - loss: 0.5701 - accuracy: 0.7236 - 258ms/epoch - 321us/step
Epoch 70/100
804/804 - 0s - loss: 0.5698 - accuracy: 0.7230 - 258ms/epoch - 321us/step
Epoch 71/100
804/804 - 0s - loss: 0.5704 - accuracy: 0.7220 - 259ms/epoch - 322us/step
Epoch 72/100
804/804 - 0s - loss: 0.5709 - accuracy: 0.7230 - 258ms/epoch - 321us/step
Epoch 73/100
804/804 - 0s - loss: 0.5696 - accuracy: 0.7226 - 258ms/epoch - 321us/step
Epoch 74/100
804/804 - 0s - loss: 0.5701 - accuracy: 0.7226 - 258ms/epoch - 320us/step
Epoch 75/100
804/804 - 0s - loss: 0.5684 - accuracy: 0.7224 - 259ms/epoch - 322us/step
Epoch 76/100
804/804 - 0s - loss: 0.5727 - accuracy: 0.7216 - 257ms/epoch - 320us/step
Epoch 77/100
804/804 - 0s - loss: 0.5713 - accuracy: 0.7201 - 273ms/epoch - 339us/step
Epoch 78/100
804/804 - 0s - loss: 0.5712 - accuracy: 0.7200 - 259ms/epoch - 322us/step
Epoch 79/100
804/804 - 0s - loss: 0.5706 - accuracy: 0.7199 - 260ms/epoch - 324us/step
Epoch 80/100
804/804 - 0s - loss: 0.5729 - accuracy: 0.7210 - 257ms/epoch - 319us/step
Epoch 81/100
804/804 - 0s - loss: 0.5727 - accuracy: 0.7234 - 258ms/epoch - 320us/step
Epoch 82/100
804/804 - 0s - loss: 0.5696 - accuracy: 0.7237 - 257ms/epoch - 320us/step
Epoch 83/100
804/804 - 0s - loss: 0.5713 - accuracy: 0.7235 - 259ms/epoch - 322us/step
Epoch 84/100
804/804 - 0s - loss: 0.5711 - accuracy: 0.7200 - 259ms/epoch - 322us/step
Epoch 85/100
804/804 - 0s - loss: 0.5696 - accuracy: 0.7224 - 258ms/epoch - 321us/step
Epoch 86/100
804/804 - 0s - loss: 0.5710 - accuracy: 0.7201 - 258ms/epoch - 321us/step
Epoch 87/100
804/804 - 0s - loss: 0.5701 - accuracy: 0.7211 - 258ms/epoch - 321us/step
Epoch 88/100
804/804 - 0s - loss: 0.5722 - accuracy: 0.7209 - 259ms/epoch - 322us/step
Epoch 89/100
804/804 - 0s - loss: 0.5672 - accuracy: 0.7239 - 260ms/epoch - 323us/step
Epoch 90/100
804/804 - 0s - loss: 0.5694 - accuracy: 0.7220 - 262ms/epoch - 325us/step
Epoch 91/100
804/804 - 0s - loss: 0.5712 - accuracy: 0.7209 - 262ms/epoch - 326us/step
Epoch 92/100
804/804 - 0s - loss: 0.5707 - accuracy: 0.7213 - 275ms/epoch - 342us/step
Epoch 93/100
804/804 - 0s - loss: 0.5715 - accuracy: 0.7210 - 261ms/epoch - 324us/step
Epoch 94/100
804/804 - 0s - loss: 0.5707 - accuracy: 0.7217 - 260ms/epoch - 323us/step
Epoch 95/100
804/804 - 0s - loss: 0.5683 - accuracy: 0.7224 - 260ms/epoch - 323us/step
Epoch 96/100
804/804 - 0s - loss: 0.5704 - accuracy: 0.7199 - 262ms/epoch - 326us/step
Epoch 97/100
804/804 - 0s - loss: 0.5693 - accuracy: 0.7202 - 260ms/epoch - 323us/step
Epoch 98/100
804/804 - 0s - loss: 0.5694 - accuracy: 0.7203 - 260ms/epoch - 323us/step
Epoch 99/100
804/804 - 0s - loss: 0.5688 - accuracy: 0.7211 - 259ms/epoch - 322us/step
Epoch 100/100
804/804 - 0s - loss: 0.5723 - accuracy: 0.7208 - 260ms/epoch - 323us/step

### Step 2: After finishing your models, display the accuracy scores achieved by each model, and compare the results.

In [97]:
print("Original Model Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Original Model Results
268/268 [==============================] - 0s 305us/step - loss: 0.5550 - accuracy: 0.7276
Loss: 0.554974377155304, Accuracy: 0.727580189704895

In [98]:
print("Alternative Model 1 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A1.evaluate(X_test_scaled, y_test)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 1 Results
268/268 [==============================] - 0s 301us/step - loss: 0.5516 - accuracy: 0.7319
Loss: 0.5515909790992737, Accuracy: 0.7318950295448303

In [99]:
print("Alternative Model 2 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A2.evaluate(X_test_scaled, y_test)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 2 Results
268/268 [==============================] - 0s 292us/step - loss: 0.5593 - accuracy: 0.7331
Loss: 0.5592763423919678, Accuracy: 0.7330612540245056

### Step 3: Save each of your alternative models as an HDF5 file.

In [100]:
# Set the file path for the first alternative model
file_path = "alternative_model1.h5"

# Export your model to a HDF5 file
nn_A1.save(file_path)

In [101]:
# Set the file path for the second alternative model
file_path = "alternative_model2.h5"

# Export your model to a HDF5 file
nn_A2.save(file_path)